// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OdysseyServer.Persistence;

namespace OdysseyServer.Persistence.Migrations
{
    [DbContext(typeof(OdysseyDbContext))]
    [Migration("20210307230741_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OdysseyServer.Persistence.Entities.AbilityDbo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("Level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("int")
                        .HasColumnName("RequiredLevel");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Ability");
                });

            modelBuilder.Entity("OdysseyServer.Persistence.Entities.AbilityStatsDbo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AbilityId")
                        .HasColumnType("bigint");

                    b.Property<int>("Attack")
                        .HasColumnType("int")
                        .HasColumnName("Attack");

                    b.Property<int>("Defence")
                        .HasColumnType("int")
                        .HasColumnName("Defence");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId")
                        .IsUnique();

                    b.ToTable("AbilityStats");
                });

            modelBuilder.Entity("OdysseyServer.Persistence.Entities.CharacterAbilitiesDbo", b =>
                {
                    b.Property<long>("AbilityId")
                        .HasColumnType("bigint");

                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("AbilityId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterAbilities");
                });

            modelBuilder.Entity("OdysseyServer.Persistence.Entities.CharacterDbo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GearTier")
                        .HasColumnType("int")
                        .HasColumnName("GearTier");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("Level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<int>("Power")
                        .HasColumnType("int")
                        .HasColumnName("Power");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Xp")
                        .HasColumnType("int")
                        .HasColumnName("Xp");

                    b.HasKey("Id");

                    b.ToTable("Character");
                });

            modelBuilder.Entity("OdysseyServer.Persistence.Entities.CharacterGroupsDbo", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("CharacterId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("CharacterGroups");
                });

            modelBuilder.Entity("OdysseyServer.Persistence.Entities.GroupDbo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IconName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IconName");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("OdysseyServer.Persistence.Entities.AbilityStatsDbo", b =>
                {
                    b.HasOne("OdysseyServer.Persistence.Entities.AbilityDbo", "Ability")
                        .WithOne("Stats")
                        .HasForeignKey("OdysseyServer.Persistence.Entities.AbilityStatsDbo", "AbilityId")
                        .HasConstraintName("FK_Ability_AbilityStats")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");
                });

            modelBuilder.Entity("OdysseyServer.Persistence.Entities.CharacterAbilitiesDbo", b =>
                {
                    b.HasOne("OdysseyServer.Persistence.Entities.AbilityDbo", "Ability")
                        .WithMany("CharacterAbilities")
                        .HasForeignKey("AbilityId")
                        .HasConstraintName("FK_CharacterAbilities_Ability")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OdysseyServer.Persistence.Entities.CharacterDbo", "Character")
                        .WithMany("CharacterAbilities")
                        .HasForeignKey("CharacterId")
                        .HasConstraintName("FK_CharacterAbilities_Characters")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("OdysseyServer.Persistence.Entities.CharacterGroupsDbo", b =>
                {
                    b.HasOne("OdysseyServer.Persistence.Entities.CharacterDbo", "Character")
                        .WithMany("CharacterGroups")
                        .HasForeignKey("CharacterId")
                        .HasConstraintName("FK_CharacterGroups_Characters")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OdysseyServer.Persistence.Entities.GroupDbo", "Group")
                        .WithMany("CharacterGroups")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("FK_CharacterGroups_Group")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("OdysseyServer.Persistence.Entities.AbilityDbo", b =>
                {
                    b.Navigation("CharacterAbilities");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("OdysseyServer.Persistence.Entities.CharacterDbo", b =>
                {
                    b.Navigation("CharacterAbilities");

                    b.Navigation("CharacterGroups");
                });

            modelBuilder.Entity("OdysseyServer.Persistence.Entities.GroupDbo", b =>
                {
                    b.Navigation("CharacterGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
